@echo off 

@REM PapyrusCompiler sslThreadSlots.psc -i=".\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

@REM PapyrusCompiler sslThreadModel.psc -i=".\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

@REM PapyrusCompiler sslThreadLibrary.psc -i=".\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler sslThreadController.psc -i=".\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

@REM PapyrusCompiler sslSystemConfig.psc -i=".\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler sslActorAlias.psc -i=".\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler sslAnimationDefaults.psc -i=".\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

@REM PapyrusCompiler sslBaseAnimation.psc -i=".\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

@REM PapyrusCompiler sslAnimationFactory.psc -i=".\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

@REM PapyrusCompiler sslBaseVoice.psc -i=".\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

@REM PapyrusCompiler sslVoiceDefaults.psc -i=".\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

@REM PapyrusCompiler sslObjectFactory.psc -i=".\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

