@echo off 
PapyrusCompiler Actor.psc -i=".\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source;.\lib\immersiveAnimation\source;.\lib\immersiveSound\source;.\lib\immersiveAnimation\source;.\lib\skyrim\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source;D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler Armor.psc -i=".\lib\sexlab\source;.\lib\racemenu\source;.\lib\sexlab\source;.\lib\creature\source;.\lib\immersiveAnimation\source;.\lib\immersiveSound\source;.\lib\immersiveAnimation\source;.\lib\skyrim\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source;D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts\TESV_Papyrus_Flags.flg"

@REM PapyrusCompiler Form.psc -i=".\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source;.\lib\immersiveAnimation\source;.\lib\immersiveSound\source;.\lib\immersiveAnimation\source;.\lib\skyrim\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source;D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts\TESV_Papyrus_Flags.flg"

@REM PapyrusCompiler Weapon.psc -i=".\lib\sexlab\source;.\lib\racemenu\source;.\lib\sexlab\source;.\lib\creature\source;.\lib\immersiveAnimation\source;.\lib\immersiveSound\source;.\lib\immersiveAnimation\source;.\lib\skyrim\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source;D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts\TESV_Papyrus_Flags.flg"

