@echo off 
PapyrusCompiler sslObjectFactory.psc -i=".\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source;D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler sslVoiceDefaults.psc -i=".\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source;D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler sslBaseVoice.psc -i=".\lib\sexlab\source;D:.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler sslActorAlias.psc -i=".\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler sslAnimationDefaults.psc -i=".\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler sslBaseAnimation.psc -i=".\lib\sexlab\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
