@echo off 

@REM PapyrusCompiler ImmersiveSoundScript.psc -i=".\lib\immersiveSound\source;.\lib\immersiveAnimation\source;.\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\sexlab\source;.\lib\creature\source;.\lib\skyrim\source;D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts\TESV_Papyrus_Flags.flg"

@REM PapyrusCompiler ImmersiveNakeAlertScript.psc -i=".\lib\immersiveSound\source;.\lib\immersiveAnimation\source;.\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\sexlab\source;.\lib\creature\source;.\lib\skyrim\source;D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts\TESV_Papyrus_Flags.flg"

@REM PapyrusCompiler ImmersiveUnconsciousScript.psc -i=".\lib\immersiveSound\source;.\lib\immersiveAnimation\source;.\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\sexlab\source;.\lib\creature\source;.\lib\skyrim\source;D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts\TESV_Papyrus_Flags.flg"

@REM PapyrusCompiler ImmersiveAnimationScript.psc -i=".\lib\immersiveAnimation\source;.\lib\immersiveSound\source;.\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\sexlab\source;.\lib\creature\source;.\lib\skyrim\source;D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler ImmersiveBreakArmor.psc -i=".\lib\immersiveAnimation\source;.\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\sexlab\source;.\lib\creature\source;.\lib\skyrim\source;D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -o="D:\work\papyrus\mod\Immersive ArmorBreak\scripts" -f="D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler ImmersiveBridge.psc -i=".\lib\immersiveAnimation\source;.\lib\po3\source;.\lib\sexlab\source;.\lib\racemenu\source;.\lib\sexlab\source;.\lib\creature\source;.\lib\skyrim\source;D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -o="D:\work\papyrus\mod\Immersive ArmorBreak\scripts"  -f="D:\Games\ModOrganizer\SkyrimSE\overwrite\Source\Scripts\TESV_Papyrus_Flags.flg"